apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : app-v1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: default
  source:
    path   : "HelmCharts/AppV1Chart"
    repoURL: "git@github.com:vladbuk/argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      # parameters:
      # - name: "container.image"
      #   value: adv4000/app1:v3

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         
