service.port: 80

ingress:
  enabled: true
  name: ingress
  className: ""
  annotations: {
    kubernetes.io/ingress.class: "gce"
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
   - host: k8s.ut.in.ua
     http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-latest-service
                port: 
                  number: 80
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: app-v1-service
                port: 
                  number: 80
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: app-v2-service
                port: 
                  number: 80
          - path: /v3
            pathType: Prefix
            backend:
              service:
                name: app-v3-service
                port: 
                  number: 80
          - path: /v4
            pathType: Prefix
            backend:
              service:
                name: app-v4-service
                port: 
                  number: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


